name: Playwright Tests
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'pnpm'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        run: pnpm i

      - name: Install Playwright
        run: pnpx playwright install --with-deps chromium

      - name: Run UI tests
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: pnpm test:ui
